# Generated by Django 5.0.6 on 2025-08-10 00:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_rename_userfollowers_userfolloing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFolloing',
            new_name='UserFollowing',
        ),
    ]
